"""
Creative brief assistant for Creator Mode.

This turns a rough user idea into a plain-language plan plus an internal prompt
that the existing blueprint generator can use without changing the render path.
"""

import json
from typing import Any, Dict, List, Optional

from engine.brain import call_deepseek_v3
from engine.text_safety import sanitize_plain_text


BRIEF_SYSTEM_PROMPT = """
You are the Creator Mode brief assistant inside MIMIC.

MIMIC is an automated Instagram Reel editor. A user gives a rough natural-language idea, then MIMIC:
1. turns the idea into a Style Blueprint,
2. matches the blueprint to the user's uploaded clips,
3. renders a short social video,
4. later lets the user refine timing and clip choices.

Your role is the alignment layer BEFORE blueprint generation.
You are not rendering the video and you have not seen the user's clips or music yet.
You must translate the user's rough idea into:
- a short, plain-language plan the user can approve or correct;
- a complete editorial intake schema that MIMIC's blueprint generator needs;
- the assumptions MIMIC is making;
- 2-4 clarifying questions when important editing choices are still unclear;
- a practical production prompt that the next blueprint generator can use as its USER DESCRIPTION.

The next blueprint generator will receive the production_prompt and then separately get target duration,
music/BPM context, and a clip-library snapshot. Because of that:
- describe clip preferences as preferences, not guaranteed assets;
- do not invent specific shots, people, places, brands, or music unless the user mentioned them;
- if the user wants fast, hype, raw, funny, luxury, documentary, etc., say it clearly so the blueprint generator does not default to the wrong mood;
- include avoid rules when they matter, because they strongly shape clip selection and pacing.

Write for average users. Use simple words. Avoid film-school language, hype, jargon, and pretentious phrasing.
Ask questions only when the answer would materially change the edit. Prefer fewer, better questions, but do not under-ask.
Good questions resolve real editing tradeoffs, such as:
- people-first memories vs polished/aesthetic shots;
- funny/raw vs clean/cinematic vs emotional/nostalgic;
- tight beat-cutting vs readable moments;
- literal captions vs generated captions vs minimal/no captions;
- whether to accept shaky or low-light clips when they show the right human moment;
- how the ending should feel.

MIMIC works best when these editorial intake fields are explicit:
- main_intent: what the reel is trying to make the viewer feel or understand;
- subject_priority: people/faces, scenery/aesthetic, product/place, action, or mixed;
- emotional_direction: funny, happy, hype, nostalgic, raw, cinematic, calm, luxury, etc.;
- pacing_style: aggressive beat cuts, fast readable, slow build, calm holds, mixed;
- music_sync_style: beat-locked, chorus/drop-led, background mood, or loose rhythm;
- clip_selection_bias: human moments, sharp visuals, story clarity, motion, aesthetics, details;
- quality_tolerance: whether shaky/low-light clips are acceptable when the moment is strong;
- caption_strategy: literal, funny, emotional, minimal, generated by MIMIC, or no captions;
- ending_strategy: biggest moment, funniest moment, soft memory, clean title/outro, loopable ending;
- avoid_rules: what would make the edit feel wrong.

Do not pretend an inferred field is confirmed. If a field is inferred, mark its confidence as "assumed".
Before approval, ask about the most important assumed or missing fields.
Return strict JSON only.
"""


BRIEF_PROMPT_TEMPLATE = """
TASK:
Read the user's latest message and the current brief. If the latest message is a correction,
update the brief. If it is a new idea, create the brief from scratch.

USER'S LATEST MESSAGE:
{message}

CURRENT BRIEF, IF ANY:
{current_brief}

Return this JSON shape:
{{
  "status": "needs_clarification",
  "summary": "One short sentence in normal language.",
  "assumptions": ["2-4 assumptions MIMIC is making"],
  "resolved_choices": ["choices already confirmed by the user"],
  "intake": {{
    "main_intent": "clear plain-language intent",
    "subject_priority": "people/faces | scenery/aesthetic | product/place | action | mixed | unknown",
    "emotional_direction": "simple mood direction",
    "pacing_style": "simple pacing style",
    "music_sync_style": "simple music sync style",
    "clip_selection_bias": "what clip choices should favor",
    "quality_tolerance": "how tolerant MIMIC should be of shaky/low-quality clips",
    "caption_strategy": "how text should behave",
    "ending_strategy": "how the reel should end",
    "avoid_rules": "most important avoids"
  }},
  "intake_confidence": {{
    "main_intent": "confirmed",
    "subject_priority": "assumed",
    "emotional_direction": "confirmed",
    "pacing_style": "confirmed",
    "music_sync_style": "assumed",
    "clip_selection_bias": "assumed",
    "quality_tolerance": "missing",
    "caption_strategy": "confirmed",
    "ending_strategy": "missing",
    "avoid_rules": "assumed"
  }},
  "vibe": ["2-4 simple vibe words"],
  "pacing": "Simple pacing description.",
  "clip_preferences": ["3-6 clip types to prefer"],
  "avoid": ["2-5 things to avoid"],
  "text_style": "Simple caption/text direction.",
  "music_direction": "Simple music/sync direction.",
  "questions": [
    {{
      "id": "people_vs_aesthetic",
      "field": "subject_priority",
      "question": "Short practical question.",
      "options": ["Recommended answer first", "Alternative", "Alternative"],
      "impact": "One short sentence explaining why this matters."
    }}
  ],
  "production_prompt": "Internal prompt for MIMIC's blueprint generator."
}}

VISIBLE FIELD RULES:
- summary: one normal sentence, no more than 18 words.
- assumptions: 2-4 short assumptions. Make hidden creative decisions visible.
- resolved_choices: short user-approved choices from clarification_answers. Empty until answered.
- intake: fill every field. Use "unknown" only when MIMIC truly should not infer a useful default.
- intake_confidence: for each intake field, use "confirmed", "assumed", or "missing".
- vibe: 2-4 simple words or short phrases.
- pacing: one short sentence about rhythm.
- clip_preferences: 3-6 concrete moment types to prefer if available.
- avoid: 2-5 things that would make the edit feel wrong.
- text_style: one short sentence about caption/text feel.
- music_direction: one short sentence about music or beat behavior.
- status: "needs_clarification" if you need answers before the user approves, otherwise "ready_for_approval".
- questions: 0-4 practical questions. Use simple options. The first option should be your smart default.

CLARIFICATION RULES:
- If the current brief contains clarification_answers, fold those answers into the plan, include them in resolved_choices, update production_prompt, and return "ready_for_approval" unless something major is still missing.
- If the user prompt is broad or subjective, ask 3-4 questions instead of silently guessing.
- If an intake field is assumed or missing and it would change clip selection, pacing, captions, music sync, shot tolerance, or ending, ask about it.
- Question priority for social reels: subject_priority first, then clip_selection_bias, pacing_style/music_sync_style, caption_strategy, quality_tolerance, ending_strategy.
- Do not ask more than 4 questions in one response.
- Do not ask about facts MIMIC can infer later from the uploaded clips or music.
- Do not ask generic questions like "Anything else?".
- Ask about choices that change clip selection, pacing, captions, music sync, quality tolerance, or ending.

PRODUCTION PROMPT RULES:
Write the production_prompt as a clear internal brief for the blueprint generator.
It should include these labeled sections in plain text:
Creator intent:
Output feel:
Subject priority:
Pacing curve:
Clip selection priorities:
Quality tolerance:
Avoid:
Text/caption direction:
Music sync:
Ending:
Blueprint bias:
Resolved user choices:

Blueprint bias should tell the generator how to behave structurally, for example:
- use fewer longer holds for calm/raw/emotional edits;
- allow denser cuts only when the user explicitly wants high energy;
- keep transitions simple unless the user asks for effects;
- make the blueprint fit real uploaded clips and treat requested shots as preferences.

Do not include JSON inside production_prompt.
Do not write a long essay. Aim for 120-220 words.
If no questions are needed, return an empty questions array.
"""


def _as_list(value: Any, fallback: List[str]) -> List[str]:
    if isinstance(value, list):
        cleaned = [str(item).strip() for item in value if str(item).strip()]
        return cleaned[:6] or fallback
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return fallback


def _safe_text(value: Any, fallback: str, limit: int = 800) -> str:
    text = str(value or "").strip()
    if not text:
        return fallback
    return text[:limit]


def _as_question_list(value: Any) -> List[Dict[str, Any]]:
    if not isinstance(value, list):
        return []

    questions: List[Dict[str, Any]] = []
    seen_ids = set()
    for index, item in enumerate(value):
        if not isinstance(item, dict):
            continue

        question = sanitize_plain_text(_safe_text(item.get("question"), "", 180), 180)
        if not question:
            continue

        raw_id = _safe_text(item.get("id"), f"decision_{index + 1}", 60).lower()
        question_id = "".join(ch if ch.isalnum() else "_" for ch in raw_id).strip("_") or f"decision_{index + 1}"
        if question_id in seen_ids:
            question_id = f"{question_id}_{index + 1}"
        seen_ids.add(question_id)

        options = [
            sanitize_plain_text(str(option).strip(), 90)
            for option in _as_list(item.get("options"), [])
            if str(option).strip()
        ][:4]

        questions.append({
            "id": question_id,
            "field": sanitize_plain_text(_safe_text(item.get("field"), "", 80), 80),
            "question": question,
            "options": options,
            "impact": sanitize_plain_text(_safe_text(item.get("impact"), "", 160), 160),
        })

    return questions[:4]


INTAKE_FIELDS = {
    "main_intent": {
        "fallback": "Create a clear short-form edit based on the user's idea.",
        "label": "Main intent",
        "question": "What should this reel mainly make people feel?",
        "options": ["A clear fun memory", "A polished visual edit", "A story with a beginning and ending"],
        "impact": "This decides the overall structure of the edit.",
    },
    "subject_priority": {
        "fallback": "mixed",
        "label": "Subject priority",
        "question": "What should MIMIC prioritize when choosing clips?",
        "options": ["People and real moments first", "Best-looking aesthetic shots first", "Balance people and aesthetics"],
        "impact": "This strongly changes which clips are selected.",
    },
    "emotional_direction": {
        "fallback": "clear, natural, social-ready",
        "label": "Emotional direction",
        "question": "What should the edit feel like emotionally?",
        "options": ["Funny and energetic", "Warm and nostalgic", "Clean and cinematic"],
        "impact": "This changes pacing, captions, and clip choices.",
    },
    "pacing_style": {
        "fallback": "fast but readable",
        "label": "Pacing",
        "question": "How should the cuts feel?",
        "options": ["Fast but still readable", "Aggressive beat cuts", "Let key moments breathe"],
        "impact": "This changes segment lengths and how tightly MIMIC cuts.",
    },
    "music_sync_style": {
        "fallback": "cut to important beats without making it chaotic",
        "label": "Music sync",
        "question": "How tightly should MIMIC follow the music?",
        "options": ["Cut to the main beats", "Cut aggressively on nearly every beat", "Use music more as background mood"],
        "impact": "This changes where cuts land and how energetic the reel feels.",
    },
    "clip_selection_bias": {
        "fallback": "strong opening shot, natural movement, clear subject moments",
        "label": "Clip bias",
        "question": "What kind of moments should win if MIMIC has to choose?",
        "options": ["Real human moments", "Cleanest and sharpest visuals", "Most motion and energy"],
        "impact": "This changes the advisor's clip ranking priorities.",
    },
    "quality_tolerance": {
        "fallback": "use practical quality, but allow imperfect clips if the moment is strong",
        "label": "Shot tolerance",
        "question": "Should MIMIC allow imperfect clips if the moment is strong?",
        "options": ["Yes, emotion matters more", "Only if they are still usable", "No, keep it polished"],
        "impact": "This decides whether shaky or low-light clips can still be used.",
    },
    "caption_strategy": {
        "fallback": "short, simple caption that matches the mood",
        "label": "Captions",
        "question": "What should captions feel like?",
        "options": ["Simple and literal", "Funny and casual", "Minimal or no captions"],
        "impact": "This changes text overlays and how direct the reel feels.",
    },
    "ending_strategy": {
        "fallback": "end cleanly on a strong readable moment",
        "label": "Ending",
        "question": "How should the reel end?",
        "options": ["Biggest energy moment", "Funny or memorable moment", "Soft clean ending"],
        "impact": "This changes the final segment and emotional payoff.",
    },
    "avoid_rules": {
        "fallback": "random cuts, forced captions, and over-flashy edits",
        "label": "Avoid",
        "question": "What would ruin this edit most?",
        "options": ["Too much scenery with no people", "Cringe or forced captions", "Cuts that feel random"],
        "impact": "This helps MIMIC reject wrong-looking choices.",
    },
}


QUESTION_PRIORITY = [
    "subject_priority",
    "clip_selection_bias",
    "pacing_style",
    "music_sync_style",
    "caption_strategy",
    "quality_tolerance",
    "ending_strategy",
    "avoid_rules",
]


def _normalize_intake(data: Any) -> Dict[str, str]:
    raw = data if isinstance(data, dict) else {}
    return {
        field: sanitize_plain_text(_safe_text(raw.get(field), config["fallback"], 220), 220)
        for field, config in INTAKE_FIELDS.items()
    }


def _normalize_confidence(data: Any) -> Dict[str, str]:
    raw = data if isinstance(data, dict) else {}
    confidence: Dict[str, str] = {}
    for field in INTAKE_FIELDS:
        value = str(raw.get(field) or "").strip().lower()
        confidence[field] = value if value in {"confirmed", "assumed", "missing"} else "assumed"
    return confidence


def _has_clarification_answers(current_brief: Optional[Dict[str, Any]]) -> bool:
    return isinstance(current_brief, dict) and isinstance(current_brief.get("clarification_answers"), dict) and bool(current_brief.get("clarification_answers"))


def _auto_questions_for_intake(intake_confidence: Dict[str, str], existing: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    existing_fields = {str(question.get("field") or "").strip() for question in existing}
    questions = list(existing)

    for field in QUESTION_PRIORITY:
        if len(questions) >= 4:
            break
        if field in existing_fields:
            continue
        if intake_confidence.get(field) not in {"assumed", "missing"}:
            continue

        config = INTAKE_FIELDS[field]
        questions.append({
            "id": field,
            "field": field,
            "question": config["question"],
            "options": config["options"],
            "impact": config["impact"],
        })

    return questions[:4]


def _ensure_production_prompt_context(production_prompt: str, intake: Dict[str, str], resolved_choices: List[str]) -> str:
    lines = [production_prompt.strip()]

    required_lines = {
        "Subject priority:": intake["subject_priority"],
        "Clip selection priorities:": intake["clip_selection_bias"],
        "Quality tolerance:": intake["quality_tolerance"],
        "Text/caption direction:": intake["caption_strategy"],
        "Music sync:": intake["music_sync_style"],
        "Ending:": intake["ending_strategy"],
        "Resolved user choices:": "; ".join(resolved_choices) if resolved_choices else "Use the approved intake defaults.",
    }

    for label, value in required_lines.items():
        if label.lower() not in production_prompt.lower():
            lines.append(f"{label} {value}")

    return sanitize_plain_text("\n".join(line for line in lines if line), 2400)


def _fallback_brief(message: str) -> Dict[str, Any]:
    cleaned = message.strip()
    summary = cleaned[:120] if cleaned else "A clear short-form edit based on your idea."

    return {
        "summary": summary,
        "status": "needs_clarification",
        "assumptions": ["MIMIC will use practical defaults unless you answer the key choices."],
        "resolved_choices": [],
        "intake": _normalize_intake({}),
        "intake_confidence": _normalize_confidence({field: "assumed" for field in INTAKE_FIELDS}),
        "vibe": ["clear", "natural", "social-ready"],
        "pacing": "Start clearly, build energy in the middle, end cleanly.",
        "clip_preferences": ["strong opening shot", "natural movement", "clear subject moments"],
        "avoid": ["random cuts", "overly flashy edits"],
        "text_style": "Short, simple caption that matches the mood.",
        "music_direction": "Cut to the main beats without making it feel chaotic.",
        "questions": [
            {
                "id": "subject_priority",
                "field": "subject_priority",
                "question": "What should MIMIC prioritize most?",
                "options": ["The clearest people or subject moments", "The best-looking shots", "The fastest energy"],
                "impact": "This changes which clips get chosen first.",
            },
            {
                "id": "clip_selection_bias",
                "field": "clip_selection_bias",
                "question": "What kind of moments should win if MIMIC has to choose?",
                "options": ["Real human moments", "Cleanest and sharpest visuals", "Most motion and energy"],
                "impact": "This changes the advisor's clip ranking priorities.",
            },
            {
                "id": "caption_strategy",
                "field": "caption_strategy",
                "question": "What should captions feel like?",
                "options": ["Simple and literal", "Funny and casual", "Minimal or no captions"],
                "impact": "This changes text overlays and how direct the reel feels.",
            },
            {
                "id": "ending_strategy",
                "field": "ending_strategy",
                "question": "How should the reel end?",
                "options": ["Biggest energy moment", "Funny or memorable moment", "Soft clean ending"],
                "impact": "This changes the final segment and emotional payoff.",
            },
        ],
        "production_prompt": (
            f"Creator intent: {cleaned or 'Create a clear short-form edit.'}\n"
            "Output feel: Clear, natural, and social-ready.\n"
            "Pacing curve: Start with a strong readable moment, build energy through the middle, and end cleanly.\n"
            "Clip selection priorities: Prefer a strong opening shot, natural movement, clear subject moments, and usable detail shots if available.\n"
            "Avoid: Random cuts, overly flashy edits, and captions that feel forced.\n"
            "Text/caption direction: Use a short caption that matches the mood.\n"
            "Music sync: Cut to important beats without making the edit chaotic.\n"
            "Resolved user choices: Use smart defaults until the user clarifies.\n"
            "Blueprint bias: Use practical segment choices that can be matched to real uploaded clips."
        ),
    }


def _resolved_choices_from_current_brief(current_brief: Optional[Dict[str, Any]]) -> List[str]:
    if not isinstance(current_brief, dict):
        return []

    answers = current_brief.get("clarification_answers")
    if not isinstance(answers, dict):
        return []

    question_lookup: Dict[str, str] = {}
    for question in current_brief.get("questions") or []:
        if isinstance(question, dict):
            qid = str(question.get("id") or "").strip()
            qtext = str(question.get("question") or "").strip()
            if qid and qtext:
                question_lookup[qid] = qtext

    resolved: List[str] = []
    for key, answer in answers.items():
        clean_answer = sanitize_plain_text(str(answer).strip(), 100)
        if not clean_answer:
            continue
        question_text = question_lookup.get(str(key), "")
        if question_text:
            resolved.append(f"{sanitize_plain_text(question_text, 90)}: {clean_answer}")
        else:
            resolved.append(clean_answer)

    return resolved[:4]


def normalize_brief(data: Dict[str, Any], message: str, current_brief: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    fallback = _fallback_brief(message)
    questions = _as_question_list(data.get("questions"))
    legacy_question = sanitize_plain_text(_safe_text(data.get("question"), "", 180), 180)
    if legacy_question and not questions:
        questions = [{
            "id": "creative_choice",
            "question": legacy_question,
            "options": [],
            "impact": "This helps MIMIC avoid guessing the edit direction.",
        }]

    intake = _normalize_intake(data.get("intake"))
    intake_confidence = _normalize_confidence(data.get("intake_confidence"))
    has_answers = _has_clarification_answers(current_brief)
    if not has_answers:
        questions = _auto_questions_for_intake(intake_confidence, questions)

    status = str(data.get("status") or "").strip().lower()
    if status not in {"needs_clarification", "ready_for_approval"}:
        status = "needs_clarification" if questions else "ready_for_approval"
    if questions and not has_answers:
        status = "needs_clarification"
    if status == "needs_clarification" and not questions:
        status = "ready_for_approval"
    resolved_choices = [
        sanitize_plain_text(v, 160)
        for v in _as_list(data.get("resolved_choices"), _resolved_choices_from_current_brief(current_brief))[:4]
    ]

    production_prompt = _ensure_production_prompt_context(
        sanitize_plain_text(_safe_text(data.get("production_prompt"), fallback["production_prompt"], 2400), 2400),
        intake,
        resolved_choices,
    )

    brief = {
        "status": status,
        "summary": sanitize_plain_text(_safe_text(data.get("summary"), fallback["summary"], 180), 180),
        "assumptions": [sanitize_plain_text(v, 120) for v in _as_list(data.get("assumptions"), fallback["assumptions"])[:4]],
        "resolved_choices": resolved_choices,
        "intake": intake,
        "intake_confidence": intake_confidence,
        "vibe": [sanitize_plain_text(v, 60) for v in _as_list(data.get("vibe"), fallback["vibe"])[:4]],
        "pacing": sanitize_plain_text(_safe_text(data.get("pacing"), fallback["pacing"], 180), 180),
        "clip_preferences": [sanitize_plain_text(v, 100) for v in _as_list(data.get("clip_preferences"), fallback["clip_preferences"])[:6]],
        "avoid": [sanitize_plain_text(v, 100) for v in _as_list(data.get("avoid"), fallback["avoid"])[:5]],
        "text_style": sanitize_plain_text(_safe_text(data.get("text_style"), fallback["text_style"], 180), 180),
        "music_direction": sanitize_plain_text(_safe_text(data.get("music_direction"), fallback["music_direction"], 180), 180),
        "question": questions[0]["question"] if questions else "",
        "questions": questions,
        "production_prompt": production_prompt,
    }

    return brief


def generate_creative_brief(message: str, current_brief: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    if not message.strip():
        raise ValueError("Message is required")

    prompt = BRIEF_PROMPT_TEMPLATE.format(
        message=message.strip(),
        current_brief=json.dumps(current_brief or {}, ensure_ascii=True, indent=2),
    )

    try:
        data = call_deepseek_v3(
            prompt=prompt,
            system_prompt=BRIEF_SYSTEM_PROMPT,
        )
        return normalize_brief(data, message, current_brief)
    except Exception as exc:
        print(f"[BRIEF] DeepSeek brief generation failed, using fallback: {exc}")
        return _fallback_brief(message)

